### ISSUE TITLE
Add support for mqtt username/password authentication

### ISSUE THREAD

**Issue by saket424** [hobbyquaker/unifi2mqtt#4]
Thanks for this project. I am able to connect using my mqtts server URL on port 8883

Could you add options to specify username and password of mqtt server so that we can secure the system from rogue publishers and subscribers ?

**Comment by hobbyquaker** [comment]
This is already possible. Just put them into the URL like e.g. `mqtts://user:password@host:8883`

**Comment by saket424** [comment]
Thanks. Will give it a whirl
